'use client';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Ticket, User, Clock, AlertCircle, CheckCircle2, Phone } from 'lucide-react';

interface ActivityItem {
  id: string;
  time: string;
  type: 'token_generated' | 'token_called' | 'token_served' | 'staff_status' | 'alert' | 'completed';
  title: string;
  description: string;
  icon: typeof Ticket;
}

const activities: ActivityItem[] = [
  {
    id: '1',
    time: '10:45 AM',
    type: 'token_generated',
    title: 'Token Generated',
    description: 'Token A112 generated by John Doe',
    icon: Ticket,
  },
  {
    id: '2',
    time: '10:42 AM',
    type: 'token_called',
    title: 'Token Called',
    description: 'Token A111 called at Counter 2',
    icon: Phone,
  },
  {
    id: '3',
    time: '10:38 AM',
    type: 'token_served',
    title: 'Token Served',
    description: 'Token A110 service completed in 8 minutes',
    icon: CheckCircle2,
  },
  {
    id: '4',
    time: '10:35 AM',
    type: 'staff_status',
    title: 'Staff Status Changed',
    description: 'Sarah took a break at Counter 1',
    icon: User,
  },
  {
    id: '5',
    time: '10:30 AM',
    type: 'alert',
    title: 'Queue Alert',
    description: 'Counter 3 wait time exceeds 15 minutes',
    icon: AlertCircle,
  },
];

const getTypeColor = (type: string) => {
  switch (type) {
    case 'token_generated':
      return 'bg-blue-100 dark:bg-blue-950 text-blue-700 dark:text-blue-400';
    case 'token_called':
      return 'bg-purple-100 dark:bg-purple-950 text-purple-700 dark:text-purple-400';
    case 'token_served':
      return 'bg-green-100 dark:bg-green-950 text-green-700 dark:text-green-400';
    case 'staff_status':
      return 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-400';
    case 'alert':
      return 'bg-amber-100 dark:bg-amber-950 text-amber-700 dark:text-amber-400';
    default:
      return 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-400';
  }
};

export function LiveOperationsFeed() {
  return (
    <Card className="overflow-hidden">
      <CardHeader>
        <CardTitle className="text-lg">Live Operations Feed</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {activities.map((activity, index) => {
            const Icon = activity.icon;
            return (
              <div key={activity.id} className="flex gap-4 pb-4 last:pb-0 last:border-0 border-b border-slate-200 dark:border-slate-800">
                {/* Timeline Dot */}
                <div className="relative flex flex-col items-center">
                  <div className={cn(
                    'w-10 h-10 rounded-lg flex items-center justify-center',
                    getTypeColor(activity.type)
                  )}>
                    <Icon className="w-5 h-5" />
                  </div>
                  {index < activities.length - 1 && (
                    <div className="w-1 h-8 bg-gradient-to-b from-slate-300 to-transparent dark:from-slate-700 mt-2" />
                  )}
                </div>

                {/* Content */}
                <div className="flex-1 pt-1">
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <p className="font-medium text-sm text-slate-900 dark:text-white">
                        {activity.title}
                      </p>
                      <p className="text-xs text-slate-600 dark:text-slate-400 mt-1">
                        {activity.description}
                      </p>
                    </div>
                    <Badge variant="secondary" className="text-xs whitespace-nowrap">
                      {activity.time}
                    </Badge>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </CardContent>
    </Card>
  );
}

import { cn } from '@/lib/utils';
